#!/usr/bin/env bash

kubectl -n coder delete secret coder-github-external-auth

kubectl -n coder create secret generic coder-github-external-auth \
  --from-literal=client-id="${GH_OAUTHAPP_CLIENT_ID}" \
  --from-literal=client-secret="${GH_OAUTHAPP_CLIENT_SECRET}"
