#!/usr/bin/env bash

kubectl -n coder create secret docker-registry ghcr-pull \
  --docker-server=ghcr.io \
  --docker-username="${GHUSER}" \
  --docker-password="${GHPAT}"

kubectl -n coder patch serviceaccount default \
  -p '{"imagePullSecrets":[{"name":"ghcr-pull"}]}'
